### PR TITLE
[DCOS-43949] Update JRE to server-jre-8u192

### PR DESCRIPTION
**Pull request by soumasish**
Closed the previous PR. Addresses, https://jira.mesosphere.com/browse/DCOS-43949

### CODE REVIEW

**Comment by soumasish** [comment]
@mpereira I just rebased with master. The JAVA_HOME has been removed from the marathon template. The idea is to keep marathon agnostic of the env.

**Comment by samvantran** [comment]
+1 to @mpereira, please update the `package_builder.py` file too.

**Comment by soumasish** [comment]
@mpereira @samvantran updated jre path in ```package_builder.py```

**Comment by elezar** [comment]
@soumasish please delete branches once they have been merged.

**Comment by soumasish** [comment]
@samvantran K will backport this to 2.4. @elezar will delete the branch after the backport.

**Comment by elezar** [comment]
How is the Backport affected by the updated Spark branching strategy?

**Comment by soumasish** [comment]
@elezar I'd say it isn't, it's a feature and was done on the master, which is being backported to a release branch. This is within the scope of the branching strategy. @akirillov please chip in.

**Comment by akirillov** [comment]
@elezar branching strategy has not yet taken the effect because we don't have a new test functionality relying on Spark 2.3. The new branching strategy will be effective in the nearest future when we start with integration testing for Spark 2.3

**Pull request merged**
