### PR TITLE
[DCOS-34447] Use assembly jar with working executor kafka client metrics.

### PR DESCRIPTION
**Pull request by porridge**

### CODE REVIEW

**Comment by porridge** [comment]
cc @samvantran @susanxhuynh - please make sure to use this jar in the next round of scale tests

**Comment by mpereira** [comment]
We should use the new JAR for the next tests but I think we should keep the existing test configs unchanged as history.

**Comment by susanxhuynh** [comment]
👍 Ok. Let's create a new set of configs for the next test like Murilo suggested.

**Comment by porridge** [comment]
Done, copies made, changes to old configs reverted.
PTAL

**Pull request merged**
