### PR TITLE
Update streaming README to use permanent spark jar

### PR DESCRIPTION
**Pull request by samvantran**
Best not to use a jar in the autodelete7d folder... so I moved it up a level

### CODE REVIEW

**Comment by porridge** [comment]
I agree we should move it out of there, but I'm not sure if to the root directory.

I don't know how much junk is there already in the root directory of this bucket (`aws s3 ls s3://infinity-artifacts.s3.amazonaws.com/` says `NoSuchBucket` for me) but I'd put it under something like `/2018-cap-jpmc` to make cleanup easier in the future.

**Comment by mpereira** [comment]
@porridge try `aws s3 ls s3://infinity-artifacts`.

**Comment by porridge** [comment]
Thanks @mpereira that worked.
So there is just a handful of files in `/`, let's try to not add more.

**Comment by elezar** [comment]
Yes, @samvantran could you move the permanent jars to a folder instead.

**Comment by elezar** [comment]
@samvantran this was addressed in 03ec1ba8bfa2b09b682196db4ea616070b60c861, so I am going to go ahead and close this.

**Pull request closed without merging**
