### PR TITLE
[SPARK-472] forward DCOS_SPACE and role from dispatcher to drivers

### PR DESCRIPTION
**Pull request by ArtRand**

### CODE REVIEW

**Comment by susanxhuynh** [comment]
@ArtRand How did you test this?

**Comment by ArtRand** [comment]
@susanxhuynh Manually right now, by inspection. We would need to release spark based on the latest master to see the effect.

**Comment by ArtRand** [comment]
@susanxhuynh I used the state.json on the agents running the drivers to check. When you `curl <agent_ip>:5051/state` it will show you (something like) the taskInfo for the driver. I confirmed that the `labels` contains a k/v pair for `DCOS_SPACE`.
Something like:
```
"role": "*",
          "labels": [
            {
              "key": "DCOS_SPACE",
              "value": "/spark"
            }
          ],
```

If you are uncomfortable merging this until there is a proper test, I understand. We can merge it later once we release a new spark version.

**Comment by susanxhuynh** [comment]
@ArtRand Thanks for the explanation, I was just curious how you tested it. Feel free to merge it at this time. If you think there should be a test later on, please keep track of the task so we don't forget.

**Pull request merged**
