### PR TITLE
check app metrics to verify monitoring

### PR DESCRIPTION
**Pull request by zmalik**
## What changes were proposed in this pull request?
 During MWT we saw that pushgateway wasn't present in the dcos-monitoring.

The observability team has said to bring it back but this was the workaround used to check if data-services app metrics were working, during the preflight check

## How were these changes tested?

During MWT15

### CODE REVIEW

**Comment by mpereira** [comment]
@akirillov we have a ticket for that, it's scheduled for the next MWT: https://jira.mesosphere.com/browse/DCOS-44091

**Comment by akirillov** [comment]
soft ping @zmalik, how shall we proceed with this PR?

**Comment by zmalik** [comment]
@akirillov if this PR https://github.com/mesosphere/dcos-monitoring/pull/170 make it to dcos-monitoring before next MWT, we could ask to enable pushgateway for MWT and we won't even need this current PR.

and these changes aren't related to spark, they just live here. So if https://jira.mesosphere.com/browse/DCOS-44091 is solved or https://github.com/mesosphere/dcos-monitoring/pull/170 is merged we won't need this PR here 

can we close this PR and leave the branch open to take changes away also when https://jira.mesosphere.com/browse/DCOS-44091 is solved ? 

cc: @mpereira

**Comment by mpereira** [comment]
Sounds good to me @zmalik.

**Pull request closed without merging**
